INSERT INTO assistant_settings (setting_key, setting_value, created_at, updated_at) VALUES
('assistant_name', 'Toto', NOW(), NOW()),
('assistant_title', 'Toto da Totalfilter', NOW(), NOW()),
('assistant_subtitle', 'Consultor digital Totalfilter', NOW(), NOW()),
('welcome_message', 'Olá. Eu sou o Toto, assistente digital da Totalfilter. Posso ajudar com produtos, orçamento, qualidade, lançamentos e contato.', NOW(), NOW()),
('input_placeholder', 'Digite sua dúvida, aplicação ou objetivo', NOW(), NOW()),
('quick_replies', "Quero um orçamento\nComo encontro o filtro certo?\nFalar com o comercial\nOnde fica a Totalfilter?", NOW(), NOW()),
('persona_description', 'Mascote-consultor da Totalfilter. Amigável, técnico na medida certa, objetivo, cordial, confiável, natural e profissional.', NOW(), NOW()),
('primary_color', '#0057A8', NOW(), NOW()),
('accent_color', '#FF8C1A', NOW(), NOW()),
('mascot_url', '/chat-widget/assets/mascot.svg', NOW(), NOW())
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), updated_at = NOW();

INSERT INTO faq_items (category, question, answer, keywords, sort_order, is_active, created_at, updated_at) VALUES
('Institucional', 'O que a Totalfilter vende?', 'A Totalfilter atua com filtros automotivos e elementos filtrantes para aplicações automotivas e outras aplicações industriais, com foco em qualidade, performance e durabilidade.', 'vende,filtros,produtos,segmento', 1, 1, NOW(), NOW()),
('Contato', 'Como entrar em contato com a Totalfilter?', 'Você pode entrar em contato pelo e-mail marketing@totalfilter.com.br ou pelos telefones (11) 97423-8992, (11) 4382-6908 e (11) 4382-7038.', 'contato,telefone,email,comercial', 2, 1, NOW(), NOW()),
('Localização', 'Onde fica a Totalfilter?', 'A Totalfilter está localizada na Rua São João do Araguaia, 512 - Jd. Califórnia, Barueri - SP.', 'endereço,localização,barueri', 3, 1, NOW(), NOW()),
('Orçamento', 'Como pedir orçamento?', 'Para solicitar orçamento, o ideal é informar o produto ou aplicação de interesse e seus dados de contato. O assistente pode registrar seu pedido e encaminhar para a equipe comercial.', 'orçamento,cotação,comprar,comercial', 4, 1, NOW(), NOW()),
('Comercial', 'Como falar com o comercial?', 'Se quiser falar com o comercial, você pode solicitar atendimento humano pelo chat ou usar os canais da empresa: marketing@totalfilter.com.br e telefones oficiais.', 'comercial,atendente,humano,retorno', 5, 1, NOW(), NOW()),
('Produtos', 'Como encontrar o filtro certo para meu veículo?', 'Para indicar o filtro mais adequado, é importante informar a aplicação, o modelo do veículo, o ano e, se possível, a referência desejada. Quando a confirmação técnica depender de validação, a equipe comercial pode complementar o atendimento.', 'filtro certo,veículo,aplicação,compatibilidade', 6, 1, NOW(), NOW()),
('Qualidade', 'Como funciona a política de qualidade?', 'A política de qualidade da Totalfilter tem foco em melhoria contínua, desempenho, sustentabilidade, atendimento ao cliente e atendimento aos requisitos legais aplicáveis.', 'qualidade,melhoria contínua,sustentabilidade', 7, 1, NOW(), NOW()),
('Lançamentos', 'Vocês têm lançamentos?', 'A Totalfilter pode divulgar lançamentos e novidades pela área de lançamentos e pelos canais comerciais. O assistente também pode direcionar você para as novidades cadastradas na base.', 'lançamentos,novidades', 8, 1, NOW(), NOW()),
('Atendimento', 'Como funciona o suporte e atendimento?', 'O atendimento da Totalfilter é orientado para suporte, pré-venda e direcionamento comercial. Quando necessário, o assistente coleta dados e encaminha a solicitação para a equipe humana.', 'suporte,pós-venda,atendimento', 9, 1, NOW(), NOW()),
('Confiabilidade', 'A empresa é confiável?', 'A Totalfilter foi iniciada em janeiro de 2018 e se posiciona com foco em inovação, qualidade, durabilidade, tecnologia, responsabilidade e atendimento ao cliente.', 'confiável,empresa,história', 10, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE answer = VALUES(answer), updated_at = NOW();

INSERT INTO knowledge_pages (slug, title, excerpt, content, source_type, source_url, keywords, priority, is_active, created_at, updated_at) VALUES
('institucional-totalfilter', 'Institucional Totalfilter', 'Resumo institucional da Totalfilter para atendimento digital.', 'A Totalfilter atua com filtros automotivos de alta qualidade e performance para veículos leves e pesados. Também trabalha com elementos filtrantes para aplicações automotivas e outras aplicações industriais. A empresa foi iniciada em janeiro de 2018 e mantém foco em inovação, qualidade, durabilidade, tecnologia, responsabilidade e atendimento ao cliente.', 'seed', 'https://www.totalfilter.com.br', 'institucional,empresa,história,valores', 10, 1, NOW(), NOW()),
('politica-qualidade', 'Política de Qualidade', 'Diretrizes públicas da política de qualidade da Totalfilter.', 'A política de qualidade da Totalfilter tem foco em melhoria contínua, desempenho, sustentabilidade e atendimento aos requisitos legais aplicáveis, sempre buscando fortalecer a confiança dos clientes e a consistência dos produtos.', 'seed', 'https://www.totalfilter.com.br', 'qualidade,melhoria contínua,desempenho,sustentabilidade', 9, 1, NOW(), NOW()),
('canais-atendimento', 'Canais de Atendimento', 'Canais públicos da Totalfilter para contato e localização.', 'E-mail: marketing@totalfilter.com.br. Telefones: (11) 97423-8992, (11) 4382-6908 e (11) 4382-7038. Endereço: Rua São João do Araguaia, 512 - Jd. Califórnia, Barueri - SP.', 'seed', 'https://www.totalfilter.com.br', 'contato,telefone,email,endereço,barueri', 8, 1, NOW(), NOW()),
('pre-venda-e-cotacao', 'Pré-venda e Cotação', 'Como o assistente deve conduzir pedidos de orçamento.', 'Em fluxos de intenção de compra, o assistente deve atuar de forma consultiva, ajudando a organizar a solicitação com nome, telefone, e-mail, empresa, cidade/estado, produto de interesse e mensagem livre. Quando houver necessidade de confirmação comercial, o atendimento deve ser encaminhado para a equipe humana.', 'seed', NULL, 'orçamento,cotação,lead,pré-venda', 7, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE excerpt = VALUES(excerpt), content = VALUES(content), updated_at = NOW();

INSERT INTO product_index (product_code, product_name, category, application_summary, technical_notes, status_label, product_url, keywords, is_launch, is_active, created_at, updated_at) VALUES
('TF-AR-001', 'Filtro de Ar Premium Totalfilter', 'Filtros automotivos', 'Indicado para aplicações automotivas em que se busca alta eficiência de retenção e bom desempenho em rotinas de uso severo e urbano.', 'Confirmar aplicação exata com modelo, ano e referência do veículo antes da venda.', 'Linha principal', NULL, 'filtro de ar,automotivo,leve,pesado', 0, 1, NOW(), NOW()),
('TF-OLEO-014', 'Filtro de Óleo Performance Totalfilter', 'Filtros automotivos', 'Projetado para contribuir com a proteção do sistema de lubrificação e a durabilidade do motor, com foco em desempenho e confiança.', 'Não informar compatibilidade sem validação da referência correta.', 'Linha principal', NULL, 'filtro de óleo,motor,lubrificação', 0, 1, NOW(), NOW()),
('TF-COMB-020', 'Filtro de Combustível Totalfilter', 'Filtros automotivos', 'Solução voltada para controle de impurezas no sistema de combustível, atendendo demandas de veículos leves e pesados conforme aplicação.', 'Oriente coleta de dados da aplicação antes de indicar o item.', 'Linha principal', NULL, 'filtro de combustível,leve,pesado', 0, 1, NOW(), NOW()),
('TF-LANC-101', 'Elemento Filtrante Linha Lançamento 101', 'Lançamentos', 'Novo item cadastrado para ampliar o portfólio de aplicações da Totalfilter, com foco em performance e durabilidade.', 'Detalhes técnicos completos devem ser confirmados pela equipe comercial ou catálogo interno.', NULL, NULL, 'lançamento,novidade,elemento filtrante', 1, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE application_summary = VALUES(application_summary), updated_at = NOW();
